### ISSUE TITLE
new gui

### ISSUE THREAD

**Issue by ghost1372** [stanac/shutdown#6]
Hi if you want, I can make a better appearance for this app
If you agree, I will soon create a PR

**Comment by stanac** [comment]
Hi. I have nothing against that :)

**Comment by stanac** [comment]
@ghost1372 there are multiple problems with your PR, some of those problems are:
1. When settings are visible some controls that should be, are not fully visible (blink option), and others controls from main window are visible and they shouldn't be (operation selection). Please check screenshot.
2. Selecting operation doesn't work (it actually does work in view-model, however there is no UI response so it's not clear which operation is selected).
3. Force button should act as checkbox, and with your changes it's not clear in which state that button is.
4. You say it's better appearance, however that's open to user preference, honestly I like better how it looks without your PR, so I would suggest to make a setting so user can choose theme, old one or new one where default one is old one.

As you say in PR comment main window (and VM) are quite complex, app would benefit more from refactoring main window into multiple components. Don't get me wrong, I am not asking you to refactor. But it would be less work to refactor and than apply theme changes, wrt doing it in the other way around (first apply theme then refactor).

I will have to reject your pull request. I will leave the issue open.


![image](https://user-images.githubusercontent.com/8450675/47029899-df6dfa80-d16c-11e8-8961-35024c822e99.png)
